# -*- coding: utf-8 -*-
"""Module_4_FakeAlbumCoverGame_v0.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SRehhGiBaxXJpDvh-_mC7W92xASIEI1W

#Make Fake Album Cover Game

## Table of Contents
Our goal is to create randomly generated album covers with:

<div class="alert alert-block alert-info" style="margin-top: 20px">
<ol>

<li><a href="#ref1">Learn how to use the function display_cover</a></li>
<li><a href="#ref2">Loading a random page from Wikipedia</a></li>
<li><a href="#ref3">Extracting the Title of the Article</a></li>
<li><a href="#ref4"> Displaying the Album Cover</a></li>


</ol>
<br>
<p></p>
Estimated Time Needed: <strong>60 min</strong>
</div>

<hr>

Inspiration: [Fake Album Covers](https://fakealbumcovers.com/)

#### Import libraries
"""

from IPython.display import Image as IPythonImage
from PIL import Image
from PIL import ImageFont
from PIL import ImageDraw

"""##Download the image and then upload the image into colab using the File Upload option (left side)

#### Helper function to superimpose text on image
"""

def display_cover(top,bottom):
    """This function
    """
    import requests
    
    name = 'album_art_raw.png'
    # Now let's make get an album cover.
    # https://picsum.photos/ is a free service that offers random images.
    # Let's get a random image:
    album_art_raw = requests.get('https://picsum.photos/500/500/?random')
    
    #print('The response code 'album_art_raw.status_code)
    # and save it as 'album_art_raw.png'
    with open(name,'wb') as album_art_raw_file:
       album_art_raw_file.write(album_art_raw.content)
    # Now that we have our raw image, let's open it 
    # and write our band and album name on it
    img = Image.open("album_art_raw.png")
    draw = ImageDraw.Draw(img)

    # the x,y coordinates for where our album name and band name text will start
    # counted from the top left of the picture (in pixels)
    band_x, band_y = 50, 50
    album_x, album_y = 50, 400

    # Our text should be visible on any image. A good way
    # of accomplishing that is to use white text with a 
    # black border. We'll use the technique shown here to draw the border:
    # https://mail.python.org/pipermail/image-sig/2009-May/005681.html
    outline_color ="black"

    draw.text((band_x-1, band_y-1), top, fill=outline_color)
    draw.text((band_x+1, band_y-1), top, fill=outline_color)
    draw.text((band_x-1, band_y+1), top, fill=outline_color)
    draw.text((band_x+1, band_y+1), top, fill=outline_color)

    draw.text((album_x-1, album_y-1), bottom ,  fill=outline_color)
    draw.text((album_x+1, album_y-1), bottom ,  fill=outline_color)
    draw.text((album_x-1, album_y+1), bottom ,  fill=outline_color)
    draw.text((album_x+1, album_y+1), bottom ,  fill=outline_color)

    draw.text((band_x,band_y),top,(255,255,255))
    draw.text((album_x, album_y),bottom,(255,255,255))

    return img

"""## 1) Learn how to use the function display_cover <a id='ref1'></a>

The function **display_cover**  selects a random image from https://picsum.photos/  and will help us superimpose two strings over the image. The parameter **top** is the string we would like to superimpose on the top of an image.  The parameter bottom is the string we would like to display on the bottom of the image.  The function does not return the image but returns an object of type  Image from the Pillow library; the object represents a PIL image.
"""

img=display_cover('top','bottom')

"""To save the image, we use the method **save** . The argument is the file  name of the image  we would like to save in this case 'sample-out.png'"""

img.save('sample-out.png')

"""Finely we use **IPythonImage** to read the image file and display the results."""

IPythonImage(filename='sample-out.png')

"""**Question 1)** Use the **display_cover** function to display the image with the name Python on the top and Data Science on the bottom. Save the image as **'sample-out.png'**."""

img=display_cover(top='Python',bottom='Data Science')
img.save('sample-out.png')

IPythonImage(filename='sample-out.png')

"""## Part 2: Loading a random page from Wikipedia  <a id='ref2'></a>

In this project, we will use the request library, we used it in the function **display_cover**, but you should import the library in the next cell.
"""

import requests

"""The following is the URL to the  page"""

wikipedia_link='https://en.wikipedia.org/wiki/Special:Random'

"""**Question 2)** Get Wikipedia page is converted to a string

Use the function **get** from the **requests** library to download the Wikipedia page using the **wikipedia_link** as an argument. Assign the object to the variable **raw_random_wikipedia_page**.
"""

#hint: requests.get()
raw_random_wikipedia_page=requests.get(wikipedia_link)

"""Use the data attribute **text** to extract the XML as a text file a string and assign the result variable **page**:"""

page = raw_random_wikipedia_page.text
print(page)

"""# Part 3: Extracting the Title of the Article <a id='ref3'></a>

**Question 3 (part 1)**  Use the title of the Wikipedia article as the title of the band. The title of the article is surrounded by the XML node title as follows:  **&lt;title&gt;title - Wikipedia&lt;/title>**
. For example, if the title of the article was Python we would see the following:  **&lt;title&gt;Python - Wikipedia&lt;/title>**. Consider the example where the title of the article is Teenage Mutant Ninja Turtles the result would be:  **&lt;title&gt;Teenage Mutant Ninja Turtles - Wikipedia&lt;/title>**.  The first step is to find the XML node  **&lt;title&gt;** and **&lt;/title&gt;**indicating the start and end of the title. The string function  **find** maybe helpful, you can also use libraries like **xlxml**.
"""

title_start=page.find('<title>')
title_end=page.find('</title>')
title=page[(title_start+7):(title_end)]
band_title=title.replace(' - Wikipedia','')

"""**Question 3 (part 2)** Next get rid of the term ** - Wikipedia** from the title and assign the result to the **band_title**  For example you can use the function or method **strip** or **replace**.

**Question 4)** Repeat the second and third step, to extract the title of a second Wikipedia article but use the result to **album_title**
"""

raw_random_wikipedia_page=requests.get(wikipedia_link)
page = raw_random_wikipedia_page.text
title_start=page.find('<title>')
title_end=page.find('</title>')
title=page[(title_start+7):(title_end)]
album_title=title.replace(' - Wikipedia','')

"""If you did everything correct the following cell should display the album and band name:"""

print("Your band: ", band_title)
print("Your album: ", album_title)

"""## Part 4: Displaying the Album Cover  <a id='ref4'></a>

Use the function **display_cover** to superimpose the band and album title over a random image, assign the result to the variable **album_cover **.

**Question 5)** use the function display_cover  to display the album cover with two random article titles representing the name of the band and the title of the album.
"""

img=display_cover(top=band_title,bottom=album_title)

"""Use the method save to save the image as **sample-out.png**:"""

img.save('sample-out.png')

"""Use the function **IPythonImage** to display the image"""

IPythonImage(filename='sample-out.png')

