# -*- coding: utf-8 -*-
"""Module 4 Assignment pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19QW7hLnYCUiACTJ8SnclYMDUqj12CuyJ

This assignment requires more individual learning then the last one did - you are encouraged to check out the [pandas documentation](http://pandas.pydata.org/pandas-docs/stable/) to find functions or methods you might not have used yet, or ask questions on [Stack Overflow](http://stackoverflow.com/) and tag them as pandas and python related.

Upload the file into google colab by using the "Files" option in the left

### Question 1 (20%)
Load the energy data from the file `Energy Indicators.xls`, which is a list of indicators of [energy supply and renewable electricity production](Energy%20Indicators.xls) from the [United Nations](http://unstats.un.org/unsd/environment/excel_file_tables/2013/Energy%20Indicators.xls) for the year 2013, and should be put into a DataFrame with the variable name of **energy**.

Keep in mind that this is an Excel file, and not a comma separated values file. Also, make sure to exclude the footer and header information from the datafile. The first two columns are unneccessary, so you should get rid of them, and you should change the column labels so that the columns are:

`['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']`
"""

# Energy  DataFrame created and necessary operations performed

import pandas as pd
import numpy as np
 

energy1 = pd.read_excel('Energy Indicators.xls')
energy1 = energy1[17:244]
energy = pd.DataFrame(energy1)
energy.head(100)
energy.drop(energy.columns[[0,1]], axis = 1, inplace = True)
energy
#energy.drop(energy.index[[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]],axis = 0,inplace = True)
energy.head(100)
energy = energy.rename(columns= {'Unnamed: 2': 'Country','Unnamed: 3': 'Energy Supply','Unnamed: 4': 'Energy Supply per Capita', 'Unnamed: 5' : '% Renewable'})
energy
#energy = energy.set_index('Country')
energy['Energy Supply'] = energy['Energy Supply'].replace({'...': np.nan})
list(energy)
energy.head(20)
#energy.tail(10)

"""Convert `Energy Supply` to gigajoules (there are 1,000,000 gigajoules in a petajoule). For all countries which have missing data (e.g. data with "...") make sure this is reflected as `np.NaN` values."""

#dealt with missing values
energy['Energy Supply'] = energy['Energy Supply'].apply(lambda x: x * 1000000)

energy.head(10)



"""Rename the following list of countries (for use in later questions):

```"Republic of Korea": "South Korea",
"United States of America": "United States",
"United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
"China, Hong Kong Special Administrative Region": "Hong Kong"```

There are also several countries with numbers and/or parenthesis in their name. Be sure to remove these, 

e.g. 

`'Bolivia (Plurinational State of)'` should be `'Bolivia'`, 

`'Switzerland17'` should be `'Switzerland'`.

<br>
"""

#renaming performed right
energy['Country'] = energy['Country'].replace(to_replace = ['Switzerland17','Australia1'],   value =["Switzerland","Australia"])
energy['Country'] = energy['Country'].replace(to_replace = ['United Kingdom of Great Britain and Northern Ireland19','United States of America20','China, Hong Kong Special Administrative Region2','Bolivia (Plurinational State of)','China2','China, Macao Special Administrative Region4','Denmark5','France6','Falkland Islands (Malvinas)','Greenland7','Indonesia8','Iran (Islamic Republic of)','Italy9','Japan10','Kuwait11',"Lao People's Democratic Republic",'Micronesia (Federated States of)','Netherlands12','Portugal13','Saudi Arabia14','Serbia15','Sint Maarten (Dutch part)','Spain16','Ukraine18','Venezuela (Bolivarian Republic of)','Japan10','Republic of Korea'], value =["United Kingdom","United States","Hong Kong","Bolivia","China","Macao","Denmark","France","Falkland Islands","Greenland","Indonesia","Iran","Italy","Japan","Kuwait","Lao","Micronesia","Netherlands","Portugal","Saudi Arabia","Serbia","Sint Maarten","Spain","Ukraine","Venezuela","Japan","South Korea"])
energy['Country']
energy.head(300)
energy = energy.set_index('Country')
energy



"""Next, load the GDP data from the file `world_bank.csv`, which is a csv containing countries' GDP from 1960 to 2015 from [World Bank](http://data.worldbank.org/indicator/NY.GDP.MKTP.CD). Call this DataFrame **GDP**. 

Make sure to skip the header, and rename the following list of countries:

```"Korea, Rep.": "South Korea", 
"Iran, Islamic Rep.": "Iran",
"Hong Kong SAR, China": "Hong Kong"```



Finally, load the [Sciamgo Journal and Country Rank data for Energy Engineering and Power Technology](http://www.scimagojr.com/countryrank.php?category=2102) from the file `scimagojr-3.xlsx`, which ranks countries based on their journal contributions in the aforementioned area. Call this DataFrame **ScimEn**.

Join the three datasets: GDP, Energy, and ScimEn into a new dataset (using the intersection of country names). Use only the last 10 years (2006-2015) of GDP data and only the top 15 countries by Scimagojr 'Rank' (Rank 1 through 15). 

The index of this DataFrame should be the name of the country, and the columns should be ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations',
       'Citations per document', 'H index', 'Energy Supply',
       'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015'].

*This function should return a DataFrame with 20 columns and 11 entries.*
"""

#worldbank GDP  dataset loaded and necessary operations perrformed 
import csv
GDP1 = pd.read_csv('worldbank.csv')
GDP1 = GDP1[3:270] # to remove headers and footers
GDP = pd.DataFrame(GDP1)
GDP = GDP.rename(columns=GDP.iloc[0]).drop(GDP.index[0]) #setting first row as column headers
GDP['Country Name'] = GDP['Country Name'].replace(to_replace = ['Micronesia, Fed. Sts.','Hong Kong SAR, China','Iran, Islamic Rep.','Korea, Rep.'], value =["Micronesia","Hong Kong","Iran","South Korea"])
GDP.loc[GDP['Country Name'] == 'Hong Kong'] # To search for a specific row values
cols = [2006,2007,2008,2009,2010,2011,2012,2013,2014,2015]
colss = ['Country Name','Country Code','Indicator Name','Indicator Code']
col = colss + cols
print(col)
GDP = GDP.loc[:,col]

GDP = GDP.rename(columns = {'Country Name' : 'Country'})
#GDP = GDP.set_index('Country')
list(GDP)
#GDP
GDP = GDP.drop(columns = ['Country Code','Indicator Name','Indicator Code'])
GDP = GDP.set_index('Country')
GDP



#journal dataset loaded and top 15 countries considered
Journal = pd.read_excel('scimagojr.xlsx')
journal = pd.DataFrame(Journal)
journal = journal[0:15]
journal = journal.set_index('Country')
journal

# Final Dataframe consist of all 3 datasets intersection countries and inner join is performed.
final = pd.merge(journal,energy, left_on=['Country'], right_on=['Country'],how = 'inner')
final = pd.merge(final, GDP, left_on=['Country'], right_on=['Country'], how = 'inner')
final.dropna(inplace=True)
#final = final.set_index('Country')
list(final)
final

def answer_one():
    return final
answer_one()



"""### Question 2 (6.6%)
The previous question joined three datasets then reduced this to just the top 15 entries. When you joined the datasets, but before you reduced this to the top 15 items, how many entries did you lose?

*This function should return a single number.*
"""

def answer_two():
    #energy1, GDP1, journal1 = energy , GDP , journal
    m1 = pd.merge(energy, GDP, how="inner", left_on="Country", right_on="Country")
    m2 = pd.merge(energy, journal, how="inner", left_on="Country", right_on="Country")
    m3 = pd.merge(GDP, journal, how="inner", left_on="Country", right_on="Country")
    actual = pd.merge(m1, journal, how="inner", left_on="Country", right_on="Country")
    g = len(energy.index)
    r = len(GDP.index)
    p = len(journal.index)
    top = len(m1.index)
    left = len(m2.index)
    right = len(m3.index)
    all3 = len(actual.index)
    ans = g + r + p - top - left - right + all3
    return ans
answer_two()

"""%%HTML
<svg width="800" height="300">
  <circle cx="150" cy="180" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="blue" />
  <circle cx="200" cy="100" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="red" />
  <circle cx="100" cy="100" r="80" fill-opacity="0.2" stroke="black" stroke-width="2" fill="green" />
  <line x1="150" y1="125" x2="300" y2="150" stroke="black" stroke-width="2" fill="black" stroke-dasharray="5,3"/>
  <text  x="300" y="165" font-family="Verdana" font-size="35">Everything but this!</text>
</svg>

## Answer the following questions in the context of only the top 15 countries by Scimagojr Rank (aka the DataFrame returned by `answer_one()`)

### Question 3 (6.6%)
What is the average GDP over the last 10 years for each country? (exclude missing values from this calculation.)

*This function should return a Series named `avgGDP` with 15 countries and their average GDP sorted in descending order.*
"""

def avg(row):
    data = row[[2006,2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015]]
    print(data)
    return np.average(data)

def answer_three():
    Top15 = answer_one()
    Top15 = Top15[[2006,2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015]]
    avgGDP = Top15.apply(lambda x : np.average(x), axis=1)
    avgGDP = avgGDP.sort_values(ascending=False)
    return avgGDP

  
  
df = answer_three()

print(df)

"""### Question 4 (6.6%)
By how much had the GDP changed over the 10 year span for the country with the 6th largest average GDP?

*This function should return a single number.*
"""

def answer_four():
    Top15 = answer_one()
    avgGDP = answer_three()
    country = avgGDP.keys()[5]
    print(country)
    ans = Top15.loc[country, 2015] - Top15.loc[country, 2006]
    return ans
answer_four()

"""### Question 5 (6.6%)
What is the mean `Energy Supply per Capita`?

*This function should return a single number.*
"""

Top15['Energy Supply per Capita'] = Top15['Energy Supply per Capita'].convert_objects(convert_numeric=True) 
def answer_five():
    Top15 = answer_one()
    avg = np.average(Top15['Energy Supply per Capita'])
    print(avg)
    return float(avg)
answer_five()



"""### Question 6 (6.6%)
What country has the maximum % Renewable and what is the percentage?

*This function should return a tuple with the name of the country and the percentage.*
"""

def answer_six():
    Top15 = answer_one()
    m = float(np.max(Top15['% Renewable']))
    country = Top15[Top15['% Renewable'] == m].iloc[0].name
    ans = country, m
    return ans
answer_six()

"""### Question 7 (6.6%)
Create a new column that is the ratio of Self-Citations to Total Citations. 
What is the maximum value for this new column, and what country has the highest ratio?

*This function should return a tuple with the name of the country and the ratio.*
"""

def ratio(row):
    row['ratio'] = row['Self-citations'] / row['Citations']
    return row

def answer_seven():
    Top15 = answer_one()
    new = Top15.apply(ratio, axis=1)
    m = float(np.max(new['ratio']))
    country = new[new['ratio'] == m].iloc[0].name
    return country, m
answer_seven()

"""### Question 8 (6.6%)

Create a column that estimates the population using Energy Supply and Energy Supply per capita. 
What is the third most populous country according to this estimate?

*This function should return a single string value.*
"""

def answer_eight():
    Top15 = answer_one()
    new = Top15.apply(lambda x: x['Energy Supply'] / x['Energy Supply per Capita'], axis=1)
    new.sort_values(ascending=False)
    country = new.keys()[2]
    return country
answer_eight()

"""### Question 9 (6.6%)
Create a column that estimates the number of citable documents per person. 
What is the correlation between the number of citable documents per capita and the energy supply per capita? Use the `.corr()` method, (Pearson's correlation).

*This function should return a single number.*

*(Optional: Use the built-in function `plot9()` to visualize the relationship between Energy Supply per Capita vs. Citable docs per Capita)*
"""

def answer_nine():
    Top15 = answer_one().copy()
    Top15['PopEst'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    Top15['Citable docs per Capita'] = Top15['Citable documents'] / Top15['PopEst']
    Top15 = Top15.corr(method='pearson')
    ans = Top15.loc['Energy Supply per Capita', 'Citable docs per Capita']
    return ans
answer_nine()

'''def plot9():
    import matplotlib as plt
#     %matplotlib inline
    
    Top15 = answer_one()
    Top15['PopEst'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    Top15['Citable docs per Capita'] = Top15['Citable documents'] / Top15['PopEst']
    Top15.plot(x='Citable docs per Capita', y='Energy Supply per Capita', kind='scatter', xlim=[0, 0.0006])
    '''

#plot9() # Be sure to comment out plot9() before submitting the assignment!

"""### Question 10 (6.6%)
Create a new column with a 1 if the country's % Renewable value is at or above the median for all countries in the top 15, and a 0 if the country's % Renewable value is below the median.

*This function should return a series named `HighRenew` whose index is the country name sorted in ascending order of rank.*
"""

def answer_ten():
    Top15 = answer_one()
    median = np.median(Top15['% Renewable'])
    for i in range(len(Top15)):
        if Top15.iloc[i]['% Renewable'] >= median:
            Top15.set_value(Top15.iloc[i].name, 'HighRenew', 1)
        else:
            Top15.set_value(Top15.iloc[i].name, 'HighRenew', 0)
    Top15 = Top15['HighRenew']
    Top15 = Top15.sort_values(inplace=False)
    return Top15
answer_ten()

"""### Question 11 (6.6%)
Use the following dictionary to group the Countries by Continent, then create a dateframe that displays the sample size (the number of countries in each continent bin), and the sum, mean, and std deviation for the estimated population of each country.

```python
ContinentDict  = {'China':'Asia', 
                  'United States':'North America', 
                  'Japan':'Asia', 
                  'United Kingdom':'Europe', 
                  'Russian Federation':'Europe', 
                  'Canada':'North America', 
                  'Germany':'Europe', 
                  'India':'Asia',
                  'France':'Europe', 
                  'South Korea':'Asia', 
                  'Italy':'Europe', 
                  'Spain':'Europe', 
                  'Iran':'Asia',
                  'Australia':'Australia', 
                  'Brazil':'South America'}
```

*This function should return a DataFrame with index named Continent `['Asia', 'Australia', 'Europe', 'North America', 'South America']` and columns `['size', 'sum', 'mean', 'std']`*
"""

ContinentDict  = {'China':'Asia',
                  'United States':'North America',
                  'Japan':'Asia',
                  'United Kingdom':'Europe',
                  'Russian Federation':'Europe',
                  'Canada':'North America',
                  'Germany':'Europe',
                  'India':'Asia',
                  'France':'Europe',
                  'South Korea':'Asia',
                  'Italy':'Europe',
                  'Spain':'Europe',
                  'Iran':'Asia',
                  'Australia':'Australia',
                  'Brazil':'South America'}

def answer_eleven():
    Top15 = answer_one()
    Top15['PopEst'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    for i in range(len(Top15)):
        country = Top15.iloc[i].name
        Top15.set_value(country, 'Continent', ContinentDict[country])
    Top15 = (Top15.reset_index(level=0)
                 .set_index(['Continent', 'Country']))
    Top15 = Top15.groupby(level=0)['PopEst'].agg({'size': np.size, 'sum': np.sum, 'mean': np.average, 'std': np.std})
    return Top15
answer_eleven()

"""### Question 12 (6.6%)
Cut % Renewable into 5 bins. Group Top15 by the Continent, as well as these new % Renewable bins. How many countries are in each of these groups?

*This function should return a __Series__ with a MultiIndex of `Continent`, then the bins for `% Renewable`. Do not include groups with no countries.*
"""

def answer_twelve():
    Top15 = answer_one()
    for i in range(len(Top15)):
        country = Top15.iloc[i].name
        Top15.set_value(country, 'Continent', ContinentDict[country])
    Top15 = (Top15.reset_index(level=0)
                 .set_index(['Continent', 'Country']))
    Top15 = pd.cut(Top15['% Renewable'], 5)
    Top15 = (Top15.reset_index()
                .set_index(['Continent', '% Renewable']))
    Top15 = Top15.groupby(level=['Continent', '% Renewable']).size()
    return Top15
answer_twelve()

"""### Question 13 (6.6%)
Convert the Population Estimate series to a string with thousands separator (using commas). Do not round the results.

e.g. 317615384.61538464 -> 317,615,384.61538464

*This function should return a Series `PopEst` whose index is the country name and whose values are the population estimate string.*
"""

def answer_thirteen():
    Top15 = answer_one()
    Top15['PopEst'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    Top15 = Top15['PopEst']
    for i in range(len(Top15)):
        country = Top15.keys()[i]
        number = "{:,}".format((Top15.iloc[i]))
        Top15.replace(Top15.iloc[i], number, inplace=True)
    return Top15
answer_thirteen()

"""### Optional

Use the built in function `plot_optional()` to see an example visualization.
"""

'''def plot_optional():
    import matplotlib as plt
#     %matplotlib inline
    Top15 = answer_one()
    ax = Top15.plot(x='Rank', y='% Renewable', kind='scatter', 
                    c=['#e41a1c','#377eb8','#e41a1c','#4daf4a','#4daf4a','#377eb8','#4daf4a','#e41a1c',
                       '#4daf4a','#e41a1c','#4daf4a','#4daf4a','#e41a1c','#dede00','#ff7f00'], 
                    xticks=range(1,16), s=6*Top15[2014]/10**10, alpha=.75, figsize=[16,6]);

    for i, txt in enumerate(Top15.index):
        ax.annotate(txt, [Top15['Rank'][i], Top15['% Renewable'][i]], ha='center')

    print("This is an example of a visualization that can be created to help understand the data. \
This is a bubble chart showing % Renewable vs. Rank. The size of the bubble corresponds to the countries' \
2014 GDP, and the color corresponds to the continent.") '''

#plot_optional() # Be sure to comment out plot_optional() before submitting the assignment!

